### ISSUE TITLE
Does not work since I updated to El Capitan 10.11.5

### ISSUE THREAD

**Issue by hoeni** [janv/usgerman#2]
This was working like a charm for years for me until I updated my OS X to El Capitan 10.11.5 today (it was an automatic offered update).
Now, this layout is not listed anymore in the preferences, though still present in `/Library/Keyboard Layouts`.

There are people having strange keyboard issues too, looking related with this one, but could not find any solution for this:

- [10.11.5 update took away my UK keyboard](http://www.ukclique.com/10-11-5-update-took-away-t816570)
- [OS 10.11.5 update resets keyboard layout](https://discussions.apple.com/thread/7564275?start=0&tstart=0)

Does anyone have an idea how this could be fixed (or even investigated)?

**Comment by janv** [comment]
That is weird. I also updated to 10.11.5 but it still works like before

**Comment by iGeorgeX** [comment]
Works for me with 10.11.5 as well. I think if 10.11.5 has problems with certain keyboard layouts it's not related to the 'usgerman' layout itself.

**Comment by hoeni** [comment]
That's really weird, so I'll try to investigate further.
Thanks for your feedback that it should be working with 10.11.5

**Comment by hoeni** [comment]
Ok, i reinstalled the file to /Library/Keyboard Layouts (which probably wasn't necessary), rebooted and then found the entry again, filed under "English". I'm not sure, but it could be I overlooked that before and was just looking in "Deutsch" before and did a search for "us" which did not match to "U.S.".
Have the entries been filed under these categories before or is that a new feature, I remember that as beeing a flat list before?

Anyway I have to state that the installation of the OS X update seems to have reset my keyboard settings.

Now everything is fine again :-) It would have been a sad future without my beloved keyboard layout :-)

**Comment by janv** [comment]
Nice :)

I'll close this then
